# $$Pandas$$

- Pandas is a python library --- `Panel Data`
- that makes working with tabular data easy
- provides fast, flexible, and expressive data structures designed to make working with tables easy
- Tabular data with heterogeneously-typed columns, as in an SQL table or Excel spreadsheet
- [Documentation](https://pandas.pydata.org/docs/getting_started/overview.html)
- 
- Data Structures in pandas are:

Dimensions | Name | Description
----|---|---
1 | Series  | 1D   labeled homogeneously-typed array
2 | DataFrame | General 2D   labeled, size-mutable tabular structure with potentially heterogeneously-typed column

![](https://pandas.pydata.org/docs/_images/01_table_dataframe.svg)

- main purpose is commonly ---> data prepration / data pre-processing
- You can explore, clean, and transform data before analytics or building ML Models
- 
-  we can :
    - Read from csv files
    - select rows and columns
    - filter, sort, group data
    - handle missing values
    - prepare data for analytics or ML

In [89]:
# pip install pandas

In [90]:
# creating a series object

import numpy as np
import pandas as pd

data = np.arange(1,10)* 10
type(data) # array

series_a = pd.Series(data, name= "data")
print(series_a)
# you will observe index has been added

type(series_a)

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
8    90
Name: data, dtype: int64

pandas.Series

In [ ]:
dataframe_a = pd.DataFrame(data) # dataframe of a single column

# we combined a lot of series objects together
dataframe_a = pd.DataFrame([series_a,series_a,series_a,series_a]) # the name will turn to label
dataframe_a

# Transpose a Data Frame
pd.DataFrame([series_a, series_a, series_a, series_a]).T

   data  data  data  data
0    10    10    10    10
1    20    20    20    20
2    30    30    30    30
3    40    40    40    40
4    50    50    50    50
5    60    60    60    60
6    70    70    70    70
7    80    80    80    80
8    90    90    90    90

In [ ]:
# Dictionary to create a dataframe
# Every key becomes a column
data = {
    "student": ["aqilah","Nazihah","Alia"],
    "maths": [88, 92, 85],
    "science": [95,96,98],
    "physics": [68, 78, 61]
}

marks_df = pd.DataFrame(data)
marks_df

   student  maths  science  physics
0   aqilah     88       95       68
1  Nazihah     92       96       78
2     Alia     85       98       61

#### Data structures
- SERIES:
    - INDEX ---> number assigned to each row
    - No label---> assigned to columns
    - Name - can have a series name

- DATAFRAME:
    - LABEL ---> column name --- By default it will serially done ---
        - starts from 0 
    - INDEX ---> number for each row
    - 
- Create:
    - using lists, arrays, dictionaries, list of dictionaries
    - use structured data to create dataframes
        - rreading a csv file, or an SQL file, or any spreadsheet .xslx

#### Exercise
1. Create a `pd.Series` with 5 temperature values and print it.
2. Create a pd.DataFrame with columns "`City`" and "`Temperature`" for 3 cities.
3. Check the `type()` of each object you created.
4. Add a name to your Series and print it again.

In [ ]:
# city's temperature
city_temps = {
    "City": ["Kuala Lumpur", "Leipzig", "Kashmir", "London", "Tokyo"],
    "Temperature": [31, 7, 10, 23, 25]
}

# lists are flexible
# we can miss a key value pair
# this results in Missing values
city_temps = [
    {"city": "Kuala Lumpur", "Temperature":31},
    {"city": "Leipzig", "Temperature":7},
    {"city": "Kashmir", "Temperature":10},
    {"city": "London", "Temperature":23},
    {"city": "Tokyo"},
    {"city": "Helsiki" , "Temperature": None}
]
 
temp_df = pd.DataFrame(city_temps)
temp_df

           city  Temperature
0  Kuala Lumpur         31.0
1       Leipzig          7.0
2       Kashmir         10.0
3        London         23.0
4         Tokyo          NaN
5       Helsiki          NaN

#### Nan Values
- Missing Values - 
    - np.nan in a dataframe
    - or we can also have None type data in a dataframe
- A database takes all the entries of a form at once
    - list of dictionaries is more suitable
    - in this situation, sometimes a key value pair can go missing 
    - or not reach the database
- other situations:
    - sensor errors
    - incomplete form submissions 
    -

#### Reading from CSV file
- CSV - Comma Separated Values
- Let's download a csv file from here [>>>> Link...](https://github.com/yannie28/Global-Superstore/blob/master/Global_Superstore(CSV).csv)
-

In [116]:
path = r"C:\Users\devid\Desktop\Nexperts Academy\AIML-nexperts4\Resources\Global_Superstore(CSV).csv"
df_sales = pd.read_csv(path)
df_sales.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,11/11/2014,11/13/2014,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,221.98,2,0.0,62.15,40.77,High
1,26341,IN-2014-JR162107-41675,2/5/2014,2/7/2014,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.40,9,0.1,-288.77,923.63,Critical

In [114]:
marks_df

# Export a dataframe too
marks_df.to_csv("marks.csv", index = False)

We now have the DATAFRAMES

### Basic Exploration Methods in Pandas
- to explore data/ dataframes
- 

- some methods that can be used on DataFrames
    - `df.head()` - first 5 records/rows
    - `df.tail` - ending 5
    - `df.sample()` - random entry from df
    - pass in the argument for how many records you want
    - `df.info()` - basic information about df
    - `df.describe()` - statistical information about the df

- .shape
- .dtypes
- .columns
- .size

In [97]:
marks_df.head()
marks_df.tail()
marks_df.sample()

   student  maths  science  physics
1  Nazihah     92       96       78

In [117]:
df_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          1000 non-null   int64
 1   Order ID        1000 non-null   str
 2   Order Date      1000 non-null   str
 3   Ship Date       1000 non-null   str
 4   Ship Mode       1000 non-null   str
 5   Customer ID     1000 non-null   str
 6   Customer Name   1000 non-null   str
 7   Segment         1000 non-null   str
 8   Postal Code     194 non-null    float64
 9   City            1000 non-null   str
 10  State           1000 non-null   str
 11  Country         1000 non-null   str
 12  Region          1000 non-null   str
 13  Market          1000 non-null   str
 14  Product ID      1000 non-null   str
 15  Category        1000 non-null   str
 16  Sub-Category    1000 non-null   str
 17  Product Name    1000 non-null   str
 18  Sales           1000 non-null   float64
 19  Quantity        1000 non-null   int64
 20  Discount        1000 non-null   float64
 21  Profit          1000 non-null   float64
 22  Shipping Cost   1000 non-null   float64
 23  Order Priority  1000 non-null   str
dtypes: float64(5), int64(2), str(17)
memory usage: 187.6 KB

In [ ]:
df_sales.describe() # only for the numerical columns
# to check the statistics
#

,Row ID,Postal Code,Sales,Quantity,Discount,Profit,Shipping Cost
count,1000.000000,194.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000
mean,25079.328000,53966.170103,1710.971470,5.55800,0.092840,288.920440,272.384897
std,12897.726632,33734.306466,1259.239238,2.71846,0.148666,574.504782,176.160716
min,58.000000,2920.000000,1.910000,1.00000,0.000000,-3059.820000,1.070000
25%,15118.750000,19134.000000,826.907500,4.00000,0.000000,10.037500,209.827500
50%,25084.500000,60564.000000,1585.115000,5.00000,0.000000,190.685000,258.897500
75%,34524.000000,88187.500000,2477.812500,7.00000,0.150000,518.872500,351.070250
max,51284.000000,98198.000000,9892.740000,14.00000,0.800000,4946.370000,923.630000

In [ ]:
# can implement these methods on series too
df_sales.Quantity
df_sales['Quantity'].describe()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          1000 non-null   int64
 1   Order ID        1000 non-null   str
 2   Order Date      1000 non-null   str
 3   Ship Date       1000 non-null   str
 4   Ship Mode       1000 non-null   str
 5   Customer ID     1000 non-null   str
 6   Customer Name   1000 non-null   str
 7   Segment         1000 non-null   str
 8   Postal Code     194 non-null    float64
 9   City            1000 non-null   str
 10  State           1000 non-null   str
 11  Country         1000 non-null   str
 12  Region          1000 non-null   str
 13  Market          1000 non-null   str
 14  Product ID      1000 non-null   str
 15  Category        1000 non-null   str
 16  Sub-Category    1000 non-null   str
 17  Product Name    1000 non-null   str
 18  Sales           1000 non-null   float64
 19  Quantity        1000 non-null   int64
 20  Discount        1000 non-null   float64
 21  Profit          1000 non-null   float64
 22  Shipping Cost   1000 non-null   float64
 23  Order Priority  1000 non-null   str
dtypes: float64(5), int64(2), str(17)
memory usage: 187.6 KB

## Basic data accessing in a dataframe

- SELECTION methods
- access a single column --- using `[]` or `.` operator
    - `df['column_name']` ---> Return a series object
    - show the `name` and the `data type` as well
    - 
- accessing multiple columns ---> 
    - `df[[col1, col2, col3]]` ---> specific columns
- access a value in a column
    - `df['column_name'][index_value]` ---> gets to a particular value

- access a new column, that does not exist, it creates a new column
    - df['new_column_name'] = # define what goes into the column

In [98]:
temp_df['city'][5]
type(temp_df['city'][5])

type(temp_df['Temperature'][5]) # Nan values in dataframes are empty numpy values

temp_df.Temperature

0    31.0
1     7.0
2    10.0
3    23.0
4    25.0
5     NaN
Name: Temperature, dtype: float64

In [126]:
df_sales.head(1)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,11/11/2014,11/13/2014,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,221.98,2,0.0,62.15,40.77,High

In [134]:
a = np.array([100,200,300,400,500])

a[1]

a[   [3,2,4,1]   ]

array([400, 300, 500, 200])

In [ ]:
cols = ["Category", "Sub-Category","Sales", "Profit"]
df_sales[cols]

            Category Sub-Category    Sales  Profit
0         Technology       Phones   221.98   62.15
1          Furniture       Chairs  3709.40 -288.77
2         Technology       Phones  5175.17  919.97
3         Technology       Phones  2892.51  -96.54
4         Technology      Copiers  2832.96  311.52
..               ...          ...      ...     ...
995        Furniture       Tables  2614.69 -821.96
996  Office Supplies   Appliances    69.48   20.84
997       Technology      Copiers   636.78  286.50
998        Furniture    Bookcases  2751.20  110.00
999       Technology       Phones  1587.00  -76.56

[1000 rows x 4 columns]

##### Common Methods in Pandas

- some methods that can be used on DataFrames
    - .shape
    - .dtypes
    - .columns
    - .size

-

In [ ]:
df_sales.shape # (1000, 24) --- rows, columns
df_sales.dtypes # returns datatype of each column
# int64, float64, str, 

df_sales.columns # an array of columns --- pandas.Index type
df_sales.size # 24 * 1000, total elements

24000

##### Data types inside of DataFrames in Python
- often times we require to select a certain type of columns in Python
- 
- There are five main dtypes in pandas:
    - `object`: Text or mixed numeric values
    - `bool`: True or False values
    - `int64`: Integer values
    - `float64`: Floating point values
    - `datetime64`: Date and time values

In [ ]:
data = {
    # 5 columns of 5 data types
    
}

df_sample = pd.DataFrame(data)

### Temporal Data - OPTIONAL

In [145]:
from datetime import datetime

# -------------------------------
# 1. Creating a datetime column
# -------------------------------
# Example data with date strings
data = {
    'event': ['Start', 'Middle', 'End'],
    'date_str': ['2024-01-15', '2024-05-20', '2024-12-31']
}

df = pd.DataFrame(data)

In [149]:
# Convert string to datetime
df['date'] = pd.to_datetime(df['date_str'], format='%Y-%m-%d', errors='coerce')

df.dtypes

event                  str
date_str               str
date        datetime64[us]
dtype: object

In [153]:
# -------------------------------
# 2. Extracting date components
# -------------------------------
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['weekday'] = df['date'].dt.day_name()

In [ ]:
# -------------------------------
# 3. Filtering by date range
# -------------------------------
start_date = '2024-05-01'
end_date = '2024-12-31'
mask = (df['date'] >= start_date) & (df['date'] <= end_date)
filtered_df = df.loc[mask]

In [ ]:
# -------------------------------
# 4. Current date & time
# -------------------------------
now = pd.Timestamp.now()
today = pd.Timestamp.today()
print("Current Timestamp:", now)
print("Today's Date:", today.date())
print(today)
print("Today's Date:", today.date())

Current Timestamp: 2026-04-08 08:07:13.068785
Today's Date: 2026-04-08
2026-04-08 08:07:13.068887
Today's Date: 2026-04-08

datetime.date(2026, 4, 8)

In [155]:
# -------------------------------
# 5. Date arithmetic
# -------------------------------
df['date_plus_7_days'] = df['date'] + pd.Timedelta(days=7)
df['days_since_event'] = (today - df['date']).dt.days